// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbVXWkV-S5Tpy2zJErDeQD6f4P8-th9a8',
    appId: '1:696731429349:web:00dd4c47efc53c201b670c',
    messagingSenderId: '696731429349',
    projectId: 'minikadimlar-4a06a',
    authDomain: 'minikadimlar-4a06a.firebaseapp.com',
    storageBucket: 'minikadimlar-4a06a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOhxkD4ypFRze0Nwadd3x3N1t1xRCbMdM',
    appId: '1:696731429349:android:35dde63c2356c1671b670c',
    messagingSenderId: '696731429349',
    projectId: 'minikadimlar-4a06a',
    storageBucket: 'minikadimlar-4a06a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmynkOr7RF8hQ1C8m1U6V3oGIsk6HYOGs',
    appId: '1:696731429349:ios:22954723df61feec1b670c',
    messagingSenderId: '696731429349',
    projectId: 'minikadimlar-4a06a',
    storageBucket: 'minikadimlar-4a06a.firebasestorage.app',
    iosBundleId: 'com.minikadimlar.minikAdimlar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmynkOr7RF8hQ1C8m1U6V3oGIsk6HYOGs',
    appId: '1:696731429349:ios:22954723df61feec1b670c',
    messagingSenderId: '696731429349',
    projectId: 'minikadimlar-4a06a',
    storageBucket: 'minikadimlar-4a06a.firebasestorage.app',
    iosBundleId: 'com.minikadimlar.minikAdimlar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbVXWkV-S5Tpy2zJErDeQD6f4P8-th9a8',
    appId: '1:696731429349:web:1c393ac7bbedeb291b670c',
    messagingSenderId: '696731429349',
    projectId: 'minikadimlar-4a06a',
    authDomain: 'minikadimlar-4a06a.firebaseapp.com',
    storageBucket: 'minikadimlar-4a06a.firebasestorage.app',
  );
}
